#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 112
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 3

enum {
  aux_sym__terminator_token1 = 1,
  anon_sym_SEMI = 2,
  anon_sym_def = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_do = 6,
  anon_sym_end = 7,
  sym_integer = 8,
  sym_float = 9,
  anon_sym_COLON = 10,
  anon_sym_defmodule = 11,
  sym_alias = 12,
  sym_identifier = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_STAR_STAR = 18,
  sym_comment = 19,
  sym_source_file = 20,
  sym__top_level = 21,
  sym__terminator = 22,
  sym__definition = 23,
  sym_function_definition = 24,
  sym_parameter_list = 25,
  sym_function_block = 26,
  sym__expression = 27,
  sym_expression_block = 28,
  sym__literal = 29,
  sym_atom = 30,
  sym_module_definition = 31,
  sym_module_block = 32,
  sym_binary_op = 33,
  sym_unary_op = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym__terminator_repeat1 = 36,
  aux_sym_function_block_repeat1 = 37,
  aux_sym_expression_block_repeat1 = 38,
  aux_sym_module_block_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__terminator_token1] = "_terminator_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_def] = "def",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_do] = "do",
  [anon_sym_end] = "end",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_COLON] = ":",
  [anon_sym_defmodule] = "defmodule",
  [sym_alias] = "alias",
  [sym_identifier] = "identifier",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR_STAR] = "**",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__top_level] = "_top_level",
  [sym__terminator] = "_terminator",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_function_block] = "function_block",
  [sym__expression] = "_expression",
  [sym_expression_block] = "expression_block",
  [sym__literal] = "_literal",
  [sym_atom] = "atom",
  [sym_module_definition] = "module_definition",
  [sym_module_block] = "module_block",
  [sym_binary_op] = "binary_op",
  [sym_unary_op] = "unary_op",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__terminator_repeat1] = "_terminator_repeat1",
  [aux_sym_function_block_repeat1] = "function_block_repeat1",
  [aux_sym_expression_block_repeat1] = "expression_block_repeat1",
  [aux_sym_module_block_repeat1] = "module_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__terminator_token1] = aux_sym__terminator_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_end] = anon_sym_end,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_defmodule] = anon_sym_defmodule,
  [sym_alias] = sym_alias,
  [sym_identifier] = sym_identifier,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__top_level] = sym__top_level,
  [sym__terminator] = sym__terminator,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_function_block] = sym_function_block,
  [sym__expression] = sym__expression,
  [sym_expression_block] = sym_expression_block,
  [sym__literal] = sym__literal,
  [sym_atom] = sym_atom,
  [sym_module_definition] = sym_module_definition,
  [sym_module_block] = sym_module_block,
  [sym_binary_op] = sym_binary_op,
  [sym_unary_op] = sym_unary_op,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__terminator_repeat1] = aux_sym__terminator_repeat1,
  [aux_sym_function_block_repeat1] = aux_sym_function_block_repeat1,
  [aux_sym_expression_block_repeat1] = aux_sym_expression_block_repeat1,
  [aux_sym_module_block_repeat1] = aux_sym_module_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__terminator_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defmodule] = {
    .visible = true,
    .named = false,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level] = {
    .visible = false,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_block] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_module_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_module_block] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__terminator_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_operand = 2,
  field_operator = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operand, 1},
    {field_operator, 0},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 7,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 14,
  [19] = 14,
  [20] = 12,
  [21] = 15,
  [22] = 16,
  [23] = 15,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 24,
  [28] = 28,
  [29] = 29,
  [30] = 26,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 31,
  [36] = 25,
  [37] = 24,
  [38] = 38,
  [39] = 39,
  [40] = 26,
  [41] = 31,
  [42] = 25,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 38,
  [49] = 32,
  [50] = 50,
  [51] = 43,
  [52] = 52,
  [53] = 46,
  [54] = 54,
  [55] = 39,
  [56] = 54,
  [57] = 28,
  [58] = 50,
  [59] = 50,
  [60] = 54,
  [61] = 45,
  [62] = 47,
  [63] = 33,
  [64] = 34,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 32,
  [74] = 28,
  [75] = 39,
  [76] = 45,
  [77] = 46,
  [78] = 43,
  [79] = 47,
  [80] = 80,
  [81] = 38,
  [82] = 82,
  [83] = 34,
  [84] = 33,
  [85] = 85,
  [86] = 86,
  [87] = 86,
  [88] = 86,
  [89] = 89,
  [90] = 89,
  [91] = 89,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 72,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 67,
  [100] = 96,
  [101] = 70,
  [102] = 98,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 104,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 104,
  [111] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(63);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == '*') ADVANCE(60);
      if (lookahead == '+') ADVANCE(58);
      if (lookahead == '-') ADVANCE(59);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '0') ADVANCE(43);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == ';') ADVANCE(36);
      if (lookahead == '\\') SKIP(33)
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(63);
      if (lookahead == '\\') SKIP(5)
      if (lookahead == 'd') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(63);
      if (lookahead == '\\') SKIP(7)
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(2)
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '\r') SKIP(4)
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(3)
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '\r') SKIP(6)
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(56);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(52);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (lookahead == '0') ADVANCE(52);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 22:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(45);
      END_STATE();
    case 23:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(49);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(46);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(50);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(8);
      END_STATE();
    case 32:
      if (eof) ADVANCE(34);
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      if (lookahead == '\n') SKIP(0)
      if (lookahead == '\r') SKIP(32)
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__terminator_token1);
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '_') ADVANCE(26);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '_') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(22);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(27);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(23);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == 'b') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == 'x') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_defmodule);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_alias);
      if (lookahead == '.') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__terminator_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_defmodule] = ACTIONS(1),
    [sym_alias] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [sym_comment] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(108),
    [sym__top_level] = STATE(3),
    [sym__definition] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym__expression] = STATE(29),
    [sym_expression_block] = STATE(29),
    [sym__literal] = STATE(29),
    [sym_atom] = STATE(29),
    [sym_module_definition] = STATE(3),
    [sym_binary_op] = STATE(29),
    [sym_unary_op] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [aux_sym__terminator_token1] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_defmodule] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [sym_comment] = ACTIONS(5),
  },
  [2] = {
    [sym__top_level] = STATE(2),
    [sym__definition] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym__expression] = STATE(29),
    [sym_expression_block] = STATE(29),
    [sym__literal] = STATE(29),
    [sym_atom] = STATE(29),
    [sym_module_definition] = STATE(2),
    [sym_binary_op] = STATE(29),
    [sym_unary_op] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [aux_sym__terminator_token1] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(26),
    [sym_integer] = ACTIONS(29),
    [sym_float] = ACTIONS(29),
    [anon_sym_COLON] = ACTIONS(32),
    [anon_sym_defmodule] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(38),
    [anon_sym_DASH] = ACTIONS(38),
    [sym_comment] = ACTIONS(5),
  },
  [3] = {
    [sym__top_level] = STATE(2),
    [sym__definition] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym__expression] = STATE(29),
    [sym_expression_block] = STATE(29),
    [sym__literal] = STATE(29),
    [sym_atom] = STATE(29),
    [sym_module_definition] = STATE(2),
    [sym_binary_op] = STATE(29),
    [sym_unary_op] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(41),
    [aux_sym__terminator_token1] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_defmodule] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [sym_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(45), 1,
      anon_sym_SEMI,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    STATE(12), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(51), 2,
      sym_integer,
      sym_float,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(56), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [41] = 11,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(57), 1,
      anon_sym_SEMI,
    ACTIONS(59), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(61), 2,
      sym_integer,
      sym_float,
    STATE(60), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [82] = 11,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(63), 1,
      anon_sym_SEMI,
    ACTIONS(65), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      sym_integer,
      sym_float,
    STATE(54), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [123] = 9,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(71), 1,
      anon_sym_end,
    ACTIONS(75), 1,
      anon_sym_COLON,
    STATE(8), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(73), 2,
      sym_integer,
      sym_float,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(52), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [158] = 9,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_end,
    ACTIONS(87), 1,
      anon_sym_COLON,
    STATE(8), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(84), 2,
      sym_integer,
      sym_float,
    ACTIONS(90), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(52), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [193] = 9,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_end,
    STATE(7), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(73), 2,
      sym_integer,
      sym_float,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(52), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [228] = 9,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(95), 1,
      anon_sym_end,
    STATE(11), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(73), 2,
      sym_integer,
      sym_float,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(52), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [263] = 9,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(97), 1,
      anon_sym_end,
    STATE(8), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(73), 2,
      sym_integer,
      sym_float,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(52), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [298] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(101), 2,
      sym_integer,
      sym_float,
    STATE(58), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [330] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(105), 2,
      sym_integer,
      sym_float,
    STATE(50), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [362] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [394] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [426] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [458] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [490] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [522] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [554] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(123), 2,
      sym_integer,
      sym_float,
    STATE(59), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [586] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [618] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [650] = 8,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [682] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(131), 2,
      sym_integer,
      sym_float,
    STATE(64), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [711] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(133), 2,
      sym_integer,
      sym_float,
    STATE(51), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [740] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_COLON,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(135), 2,
      sym_integer,
      sym_float,
    STATE(33), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [769] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_COLON,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(137), 2,
      sym_integer,
      sym_float,
    STATE(34), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [798] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [821] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 1,
      anon_sym_STAR_STAR,
    ACTIONS(147), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(149), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(145), 6,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
  [850] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(153), 2,
      sym_integer,
      sym_float,
    STATE(63), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [879] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(77), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(155), 2,
      sym_integer,
      sym_float,
    STATE(49), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [908] = 6,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_STAR_STAR,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(159), 8,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [935] = 5,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_STAR_STAR,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 10,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [960] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [983] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_COLON,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(161), 2,
      sym_integer,
      sym_float,
    STATE(32), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1012] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_COLON,
    ACTIONS(19), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(163), 2,
      sym_integer,
      sym_float,
    STATE(43), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1041] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(165), 2,
      sym_integer,
      sym_float,
    STATE(83), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1070] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1093] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1116] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(175), 2,
      sym_integer,
      sym_float,
    STATE(84), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1145] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(177), 2,
      sym_integer,
      sym_float,
    STATE(73), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1174] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(179), 2,
      sym_integer,
      sym_float,
    STATE(78), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1203] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(183), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1226] = 7,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_COLON,
    ACTIONS(55), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      sym_integer,
      sym_float,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1255] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(187), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1278] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1301] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 11,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1324] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(169), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1343] = 5,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_STAR_STAR,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(159), 7,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1366] = 10,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 1,
      anon_sym_SEMI,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    STATE(14), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(88), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(203), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1399] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(183), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1418] = 6,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_STAR_STAR,
    ACTIONS(197), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(211), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(209), 5,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
  [1443] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(191), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1462] = 10,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(213), 1,
      anon_sym_SEMI,
    STATE(15), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(90), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(203), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1495] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(173), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1514] = 10,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(215), 1,
      anon_sym_SEMI,
    STATE(21), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(89), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(203), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1547] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(141), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1566] = 10,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(217), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(87), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(203), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1599] = 10,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(219), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(203), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1632] = 10,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(221), 1,
      anon_sym_SEMI,
    STATE(23), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(91), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(203), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1665] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(187), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1684] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(195), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1703] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_STAR_STAR,
    ACTIONS(159), 9,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1724] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(159), 10,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1743] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 8,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1763] = 4,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(227), 1,
      aux_sym__terminator_token1,
    STATE(66), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(230), 8,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1783] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
    ACTIONS(234), 8,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1803] = 5,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(236), 1,
      aux_sym__terminator_token1,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    STATE(66), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(240), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1825] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 8,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1845] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
    ACTIONS(248), 8,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1865] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
    ACTIONS(252), 8,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1885] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
    ACTIONS(256), 8,
      anon_sym_def,
      anon_sym_LPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1905] = 5,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(157), 1,
      aux_sym__terminator_token1,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(159), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1925] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(139), 1,
      aux_sym__terminator_token1,
    ACTIONS(141), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1941] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(171), 1,
      aux_sym__terminator_token1,
    ACTIONS(173), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1957] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(185), 1,
      aux_sym__terminator_token1,
    ACTIONS(187), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1973] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(189), 1,
      aux_sym__terminator_token1,
    ACTIONS(191), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1989] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(181), 1,
      aux_sym__terminator_token1,
    ACTIONS(183), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [2005] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(193), 1,
      aux_sym__terminator_token1,
    ACTIONS(195), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [2021] = 6,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(258), 1,
      aux_sym__terminator_token1,
    ACTIONS(203), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(205), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(260), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [2043] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(167), 1,
      aux_sym__terminator_token1,
    ACTIONS(169), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [2059] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(262), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [2075] = 3,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(157), 1,
      aux_sym__terminator_token1,
    ACTIONS(159), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [2091] = 4,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(157), 1,
      aux_sym__terminator_token1,
    ACTIONS(207), 1,
      anon_sym_STAR_STAR,
    ACTIONS(159), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [2109] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      aux_sym__terminator_token1,
    ACTIONS(267), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
  [2131] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(270), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
  [2153] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    ACTIONS(272), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
  [2175] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(274), 1,
      anon_sym_SEMI,
    STATE(22), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
  [2197] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(217), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
  [2219] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 1,
      anon_sym_SEMI,
    STATE(14), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
  [2241] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(43), 1,
      aux_sym__terminator_token1,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(219), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      sym__terminator,
    STATE(68), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
  [2263] = 5,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_def,
    ACTIONS(279), 1,
      anon_sym_end,
    STATE(92), 2,
      sym_function_definition,
      aux_sym_module_block_repeat1,
  [2280] = 5,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_def,
    ACTIONS(283), 1,
      anon_sym_end,
    STATE(92), 2,
      sym_function_definition,
      aux_sym_module_block_repeat1,
  [2297] = 5,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_def,
    ACTIONS(285), 1,
      anon_sym_end,
    STATE(93), 2,
      sym_function_definition,
      aux_sym_module_block_repeat1,
  [2314] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(256), 2,
      anon_sym_def,
      anon_sym_end,
  [2325] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_do,
    STATE(67), 1,
      sym_function_block,
  [2338] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_do,
    STATE(69), 1,
      sym_module_block,
  [2351] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_LPAREN,
    STATE(96), 1,
      sym_parameter_list,
  [2364] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(234), 2,
      anon_sym_def,
      anon_sym_end,
  [2375] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_do,
    STATE(99), 1,
      sym_function_block,
  [2388] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(248), 2,
      anon_sym_def,
      anon_sym_end,
  [2399] = 4,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      sym_parameter_list,
  [2412] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
  [2422] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_identifier,
  [2432] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_do,
  [2442] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym_identifier,
  [2452] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_identifier,
  [2462] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(305), 1,
      ts_builtin_sym_end,
  [2472] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_alias,
  [2482] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_identifier,
  [2492] = 3,
    ACTIONS(3), 1,
      aux_sym__terminator_token1,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 41,
  [SMALL_STATE(6)] = 82,
  [SMALL_STATE(7)] = 123,
  [SMALL_STATE(8)] = 158,
  [SMALL_STATE(9)] = 193,
  [SMALL_STATE(10)] = 228,
  [SMALL_STATE(11)] = 263,
  [SMALL_STATE(12)] = 298,
  [SMALL_STATE(13)] = 330,
  [SMALL_STATE(14)] = 362,
  [SMALL_STATE(15)] = 394,
  [SMALL_STATE(16)] = 426,
  [SMALL_STATE(17)] = 458,
  [SMALL_STATE(18)] = 490,
  [SMALL_STATE(19)] = 522,
  [SMALL_STATE(20)] = 554,
  [SMALL_STATE(21)] = 586,
  [SMALL_STATE(22)] = 618,
  [SMALL_STATE(23)] = 650,
  [SMALL_STATE(24)] = 682,
  [SMALL_STATE(25)] = 711,
  [SMALL_STATE(26)] = 740,
  [SMALL_STATE(27)] = 769,
  [SMALL_STATE(28)] = 798,
  [SMALL_STATE(29)] = 821,
  [SMALL_STATE(30)] = 850,
  [SMALL_STATE(31)] = 879,
  [SMALL_STATE(32)] = 908,
  [SMALL_STATE(33)] = 935,
  [SMALL_STATE(34)] = 960,
  [SMALL_STATE(35)] = 983,
  [SMALL_STATE(36)] = 1012,
  [SMALL_STATE(37)] = 1041,
  [SMALL_STATE(38)] = 1070,
  [SMALL_STATE(39)] = 1093,
  [SMALL_STATE(40)] = 1116,
  [SMALL_STATE(41)] = 1145,
  [SMALL_STATE(42)] = 1174,
  [SMALL_STATE(43)] = 1203,
  [SMALL_STATE(44)] = 1226,
  [SMALL_STATE(45)] = 1255,
  [SMALL_STATE(46)] = 1278,
  [SMALL_STATE(47)] = 1301,
  [SMALL_STATE(48)] = 1324,
  [SMALL_STATE(49)] = 1343,
  [SMALL_STATE(50)] = 1366,
  [SMALL_STATE(51)] = 1399,
  [SMALL_STATE(52)] = 1418,
  [SMALL_STATE(53)] = 1443,
  [SMALL_STATE(54)] = 1462,
  [SMALL_STATE(55)] = 1495,
  [SMALL_STATE(56)] = 1514,
  [SMALL_STATE(57)] = 1547,
  [SMALL_STATE(58)] = 1566,
  [SMALL_STATE(59)] = 1599,
  [SMALL_STATE(60)] = 1632,
  [SMALL_STATE(61)] = 1665,
  [SMALL_STATE(62)] = 1684,
  [SMALL_STATE(63)] = 1703,
  [SMALL_STATE(64)] = 1724,
  [SMALL_STATE(65)] = 1743,
  [SMALL_STATE(66)] = 1763,
  [SMALL_STATE(67)] = 1783,
  [SMALL_STATE(68)] = 1803,
  [SMALL_STATE(69)] = 1825,
  [SMALL_STATE(70)] = 1845,
  [SMALL_STATE(71)] = 1865,
  [SMALL_STATE(72)] = 1885,
  [SMALL_STATE(73)] = 1905,
  [SMALL_STATE(74)] = 1925,
  [SMALL_STATE(75)] = 1941,
  [SMALL_STATE(76)] = 1957,
  [SMALL_STATE(77)] = 1973,
  [SMALL_STATE(78)] = 1989,
  [SMALL_STATE(79)] = 2005,
  [SMALL_STATE(80)] = 2021,
  [SMALL_STATE(81)] = 2043,
  [SMALL_STATE(82)] = 2059,
  [SMALL_STATE(83)] = 2075,
  [SMALL_STATE(84)] = 2091,
  [SMALL_STATE(85)] = 2109,
  [SMALL_STATE(86)] = 2131,
  [SMALL_STATE(87)] = 2153,
  [SMALL_STATE(88)] = 2175,
  [SMALL_STATE(89)] = 2197,
  [SMALL_STATE(90)] = 2219,
  [SMALL_STATE(91)] = 2241,
  [SMALL_STATE(92)] = 2263,
  [SMALL_STATE(93)] = 2280,
  [SMALL_STATE(94)] = 2297,
  [SMALL_STATE(95)] = 2314,
  [SMALL_STATE(96)] = 2325,
  [SMALL_STATE(97)] = 2338,
  [SMALL_STATE(98)] = 2351,
  [SMALL_STATE(99)] = 2364,
  [SMALL_STATE(100)] = 2375,
  [SMALL_STATE(101)] = 2388,
  [SMALL_STATE(102)] = 2399,
  [SMALL_STATE(103)] = 2412,
  [SMALL_STATE(104)] = 2422,
  [SMALL_STATE(105)] = 2432,
  [SMALL_STATE(106)] = 2442,
  [SMALL_STATE(107)] = 2452,
  [SMALL_STATE(108)] = 2462,
  [SMALL_STATE(109)] = 2472,
  [SMALL_STATE(110)] = 2482,
  [SMALL_STATE(111)] = 2492,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(107),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(109),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(6),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 2),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(52),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(106),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(25),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__top_level, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__top_level, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, .production_id = 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, .production_id = 2),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 4),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 2, .production_id = 1),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_op, 2, .production_id = 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 6),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 6),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 5),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 5),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 1),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_block, 2),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_block, 2),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__terminator_repeat1, 2), SHIFT_REPEAT(66),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__terminator_repeat1, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__terminator, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_definition, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_block, 3),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_block, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_block, 3),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_block, 3),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_block, 2),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_block, 2),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_block_repeat1, 2),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__terminator, 2),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(68),
  [267] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(44),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [276] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_module_block_repeat1, 2), SHIFT_REPEAT(111),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_module_block_repeat1, 2),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [305] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_clia(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
