#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 112
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 3

enum {
  aux_sym__terminator_token1 = 1,
  anon_sym_SEMI = 2,
  anon_sym_def = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_do = 6,
  anon_sym_end = 7,
  sym_integer = 8,
  sym_float = 9,
  anon_sym_COLON = 10,
  anon_sym_defmodule = 11,
  sym_alias = 12,
  sym_identifier = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_STAR_STAR = 18,
  sym_source_file = 19,
  sym__top_level = 20,
  sym__terminator = 21,
  sym__definition = 22,
  sym_function_definition = 23,
  sym_parameter_list = 24,
  sym_function_block = 25,
  sym__expression = 26,
  sym_expression_block = 27,
  sym__literal = 28,
  sym_atom = 29,
  sym_module_definition = 30,
  sym_module_block = 31,
  sym_binary_op = 32,
  sym_unary_op = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym__terminator_repeat1 = 35,
  aux_sym_function_block_repeat1 = 36,
  aux_sym_expression_block_repeat1 = 37,
  aux_sym_module_block_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__terminator_token1] = "_terminator_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_def] = "def",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_do] = "do",
  [anon_sym_end] = "end",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_COLON] = ":",
  [anon_sym_defmodule] = "defmodule",
  [sym_alias] = "alias",
  [sym_identifier] = "identifier",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR_STAR] = "**",
  [sym_source_file] = "source_file",
  [sym__top_level] = "_top_level",
  [sym__terminator] = "_terminator",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_function_block] = "function_block",
  [sym__expression] = "_expression",
  [sym_expression_block] = "expression_block",
  [sym__literal] = "_literal",
  [sym_atom] = "atom",
  [sym_module_definition] = "module_definition",
  [sym_module_block] = "module_block",
  [sym_binary_op] = "binary_op",
  [sym_unary_op] = "unary_op",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__terminator_repeat1] = "_terminator_repeat1",
  [aux_sym_function_block_repeat1] = "function_block_repeat1",
  [aux_sym_expression_block_repeat1] = "expression_block_repeat1",
  [aux_sym_module_block_repeat1] = "module_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__terminator_token1] = aux_sym__terminator_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_end] = anon_sym_end,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_defmodule] = anon_sym_defmodule,
  [sym_alias] = sym_alias,
  [sym_identifier] = sym_identifier,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [sym_source_file] = sym_source_file,
  [sym__top_level] = sym__top_level,
  [sym__terminator] = sym__terminator,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_function_block] = sym_function_block,
  [sym__expression] = sym__expression,
  [sym_expression_block] = sym_expression_block,
  [sym__literal] = sym__literal,
  [sym_atom] = sym_atom,
  [sym_module_definition] = sym_module_definition,
  [sym_module_block] = sym_module_block,
  [sym_binary_op] = sym_binary_op,
  [sym_unary_op] = sym_unary_op,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__terminator_repeat1] = aux_sym__terminator_repeat1,
  [aux_sym_function_block_repeat1] = aux_sym_function_block_repeat1,
  [aux_sym_expression_block_repeat1] = aux_sym_expression_block_repeat1,
  [aux_sym_module_block_repeat1] = aux_sym_module_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__terminator_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defmodule] = {
    .visible = true,
    .named = false,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level] = {
    .visible = false,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_block] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_module_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_module_block] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__terminator_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_operand = 2,
  field_operator = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operand, 1},
    {field_operator, 0},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 4,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 12,
  [17] = 15,
  [18] = 18,
  [19] = 12,
  [20] = 15,
  [21] = 18,
  [22] = 18,
  [23] = 13,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 30,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 26,
  [42] = 39,
  [43] = 25,
  [44] = 30,
  [45] = 26,
  [46] = 39,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 49,
  [51] = 49,
  [52] = 48,
  [53] = 48,
  [54] = 38,
  [55] = 55,
  [56] = 56,
  [57] = 28,
  [58] = 58,
  [59] = 36,
  [60] = 34,
  [61] = 24,
  [62] = 32,
  [63] = 27,
  [64] = 35,
  [65] = 47,
  [66] = 40,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 36,
  [74] = 40,
  [75] = 35,
  [76] = 47,
  [77] = 28,
  [78] = 38,
  [79] = 27,
  [80] = 32,
  [81] = 81,
  [82] = 34,
  [83] = 24,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 85,
  [88] = 88,
  [89] = 88,
  [90] = 85,
  [91] = 88,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 71,
  [97] = 69,
  [98] = 95,
  [99] = 99,
  [100] = 67,
  [101] = 101,
  [102] = 101,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 105,
  [110] = 105,
  [111] = 103,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '+') ADVANCE(52);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '0') ADVANCE(37);
      if (lookahead == ':') ADVANCE(48);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == 'd') ADVANCE(7);
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '+') ADVANCE(52);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '0') ADVANCE(37);
      if (lookahead == ':') ADVANCE(48);
      if (lookahead == ';') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == '0') ADVANCE(46);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(9);
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(3);
      if (lookahead == '0') ADVANCE(46);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 17:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(19)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(51);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(44);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 27:
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(2);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__terminator_token1);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '_') ADVANCE(22);
      if (lookahead == 'b') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(20);
      if (lookahead == 'x') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '_') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(17);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(18);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == 'b') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_defmodule);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_alias);
      if (lookahead == '.') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 6},
  [93] = {.lex_state = 6},
  [94] = {.lex_state = 6},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 6},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 19},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 19},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 19},
  [110] = {.lex_state = 19},
  [111] = {.lex_state = 19},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_defmodule] = ACTIONS(1),
    [sym_alias] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(106),
    [sym__top_level] = STATE(2),
    [sym__definition] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym__expression] = STATE(29),
    [sym_expression_block] = STATE(29),
    [sym__literal] = STATE(29),
    [sym_atom] = STATE(29),
    [sym_module_definition] = STATE(2),
    [sym_binary_op] = STATE(29),
    [sym_unary_op] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_defmodule] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
  },
  [2] = {
    [sym__top_level] = STATE(3),
    [sym__definition] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym__expression] = STATE(29),
    [sym_expression_block] = STATE(29),
    [sym__literal] = STATE(29),
    [sym_atom] = STATE(29),
    [sym_module_definition] = STATE(3),
    [sym_binary_op] = STATE(29),
    [sym_unary_op] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_def] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [anon_sym_COLON] = ACTIONS(13),
    [anon_sym_defmodule] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(17),
  },
  [3] = {
    [sym__top_level] = STATE(3),
    [sym__definition] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym__expression] = STATE(29),
    [sym_expression_block] = STATE(29),
    [sym__literal] = STATE(29),
    [sym_atom] = STATE(29),
    [sym_module_definition] = STATE(3),
    [sym_binary_op] = STATE(29),
    [sym_unary_op] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_def] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(26),
    [sym_integer] = ACTIONS(29),
    [sym_float] = ACTIONS(32),
    [anon_sym_COLON] = ACTIONS(35),
    [anon_sym_defmodule] = ACTIONS(38),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(46), 1,
      anon_sym_SEMI,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    ACTIONS(54), 1,
      anon_sym_COLON,
    STATE(15), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(52), 2,
      sym_integer,
      sym_float,
    ACTIONS(56), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(49), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [38] = 10,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_COLON,
    ACTIONS(58), 1,
      anon_sym_SEMI,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(56), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(62), 2,
      sym_integer,
      sym_float,
    STATE(51), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [76] = 10,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_COLON,
    ACTIONS(64), 1,
      anon_sym_SEMI,
    ACTIONS(66), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(56), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_integer,
      sym_float,
    STATE(50), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [114] = 8,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_end,
    ACTIONS(74), 1,
      sym_integer,
    ACTIONS(76), 1,
      sym_float,
    ACTIONS(78), 1,
      anon_sym_COLON,
    STATE(11), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(58), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [145] = 8,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      sym_integer,
    ACTIONS(76), 1,
      sym_float,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(82), 1,
      anon_sym_end,
    STATE(11), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(58), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [176] = 8,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      sym_integer,
    ACTIONS(76), 1,
      sym_float,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(84), 1,
      anon_sym_end,
    STATE(8), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(58), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [207] = 8,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      sym_integer,
    ACTIONS(76), 1,
      sym_float,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(86), 1,
      anon_sym_end,
    STATE(7), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(58), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [238] = 8,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      anon_sym_end,
    ACTIONS(93), 1,
      sym_integer,
    ACTIONS(96), 1,
      sym_float,
    ACTIONS(99), 1,
      anon_sym_COLON,
    STATE(11), 1,
      aux_sym_function_block_repeat1,
    ACTIONS(102), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(58), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [269] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [297] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [325] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [353] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(123), 1,
      sym_integer,
    ACTIONS(125), 1,
      sym_float,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(53), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [381] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [409] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(131), 1,
      sym_integer,
    ACTIONS(133), 1,
      sym_float,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(48), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [437] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [465] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [493] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    ACTIONS(141), 1,
      sym_integer,
    ACTIONS(143), 1,
      sym_float,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(52), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [521] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [549] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [577] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [605] = 3,
    ACTIONS(155), 1,
      anon_sym_STAR_STAR,
    ACTIONS(153), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
  [624] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(157), 1,
      sym_integer,
    ACTIONS(159), 1,
      sym_float,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(32), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [649] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(161), 1,
      sym_integer,
    ACTIONS(163), 1,
      sym_float,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(34), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [674] = 2,
    ACTIONS(167), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(165), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [691] = 2,
    ACTIONS(171), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(169), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [708] = 6,
    ACTIONS(155), 1,
      anon_sym_STAR_STAR,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(175), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(177), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
  [733] = 6,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(183), 1,
      sym_integer,
    ACTIONS(185), 1,
      sym_float,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(74), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [758] = 6,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(187), 1,
      sym_integer,
    ACTIONS(189), 1,
      sym_float,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(80), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [783] = 5,
    ACTIONS(155), 1,
      anon_sym_STAR_STAR,
    ACTIONS(179), 1,
      anon_sym_STAR,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    ACTIONS(153), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [806] = 6,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      sym_integer,
    ACTIONS(111), 1,
      sym_float,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(81), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [831] = 2,
    ACTIONS(153), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(151), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [848] = 2,
    ACTIONS(193), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(191), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [865] = 2,
    ACTIONS(197), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(195), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [882] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(199), 1,
      sym_integer,
    ACTIONS(201), 1,
      sym_float,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(40), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [907] = 2,
    ACTIONS(205), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(203), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [924] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(207), 1,
      sym_integer,
    ACTIONS(209), 1,
      sym_float,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(24), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [949] = 2,
    ACTIONS(213), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(211), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [966] = 6,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(215), 1,
      sym_integer,
    ACTIONS(217), 1,
      sym_float,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(60), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [991] = 6,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(219), 1,
      sym_integer,
    ACTIONS(221), 1,
      sym_float,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(61), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1016] = 6,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(223), 1,
      sym_integer,
    ACTIONS(225), 1,
      sym_float,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(62), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1041] = 6,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(227), 1,
      sym_integer,
    ACTIONS(229), 1,
      sym_float,
    ACTIONS(80), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(66), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1066] = 6,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(231), 1,
      sym_integer,
    ACTIONS(233), 1,
      sym_float,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(82), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1091] = 6,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(235), 1,
      sym_integer,
    ACTIONS(237), 1,
      sym_float,
    ACTIONS(115), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(83), 6,
      sym__expression,
      sym_expression_block,
      sym__literal,
      sym_atom,
      sym_binary_op,
      sym_unary_op,
  [1116] = 2,
    ACTIONS(241), 3,
      anon_sym_def,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(239), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1133] = 9,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    STATE(16), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(85), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(247), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1163] = 9,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(253), 1,
      anon_sym_SEMI,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(89), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(247), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1193] = 9,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(257), 1,
      anon_sym_SEMI,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(88), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(247), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1223] = 9,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(261), 1,
      anon_sym_SEMI,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(91), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(247), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1253] = 9,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(265), 1,
      anon_sym_SEMI,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(90), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(247), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1283] = 9,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(269), 1,
      anon_sym_SEMI,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(87), 1,
      aux_sym_expression_block_repeat1,
    ACTIONS(247), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1313] = 2,
    ACTIONS(205), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(203), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1328] = 4,
    ACTIONS(273), 1,
      aux_sym__terminator_token1,
    ACTIONS(275), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(277), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1347] = 3,
    ACTIONS(279), 1,
      aux_sym__terminator_token1,
    STATE(56), 1,
      aux_sym__terminator_repeat1,
    ACTIONS(282), 8,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1364] = 2,
    ACTIONS(171), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(169), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1379] = 6,
    ACTIONS(286), 1,
      sym_integer,
    ACTIONS(290), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_SLASH,
    ACTIONS(294), 1,
      anon_sym_STAR_STAR,
    ACTIONS(288), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(284), 4,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
  [1402] = 2,
    ACTIONS(197), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(195), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1417] = 2,
    ACTIONS(153), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(151), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1432] = 3,
    ACTIONS(294), 1,
      anon_sym_STAR_STAR,
    ACTIONS(153), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(151), 7,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
  [1449] = 5,
    ACTIONS(153), 1,
      sym_integer,
    ACTIONS(290), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_SLASH,
    ACTIONS(294), 1,
      anon_sym_STAR_STAR,
    ACTIONS(151), 6,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1470] = 2,
    ACTIONS(167), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(165), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1485] = 2,
    ACTIONS(193), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(191), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1500] = 2,
    ACTIONS(241), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(239), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1515] = 2,
    ACTIONS(213), 2,
      sym_integer,
      anon_sym_STAR,
    ACTIONS(211), 8,
      anon_sym_LPAREN,
      anon_sym_end,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1530] = 2,
    ACTIONS(298), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(296), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1544] = 2,
    ACTIONS(302), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(300), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1558] = 2,
    ACTIONS(306), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(304), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1572] = 2,
    ACTIONS(310), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(308), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1586] = 2,
    ACTIONS(314), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(312), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1600] = 2,
    ACTIONS(318), 2,
      anon_sym_def,
      sym_integer,
    ACTIONS(316), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_defmodule,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1614] = 2,
    ACTIONS(195), 1,
      aux_sym__terminator_token1,
    ACTIONS(197), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1627] = 2,
    ACTIONS(211), 1,
      aux_sym__terminator_token1,
    ACTIONS(213), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1640] = 2,
    ACTIONS(191), 1,
      aux_sym__terminator_token1,
    ACTIONS(193), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1653] = 2,
    ACTIONS(239), 1,
      aux_sym__terminator_token1,
    ACTIONS(241), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1666] = 2,
    ACTIONS(169), 1,
      aux_sym__terminator_token1,
    ACTIONS(171), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1679] = 2,
    ACTIONS(203), 1,
      aux_sym__terminator_token1,
    ACTIONS(205), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1692] = 2,
    ACTIONS(165), 1,
      aux_sym__terminator_token1,
    ACTIONS(167), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1705] = 4,
    ACTIONS(151), 1,
      aux_sym__terminator_token1,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(153), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1722] = 5,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(320), 1,
      aux_sym__terminator_token1,
    ACTIONS(247), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(249), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(322), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1741] = 2,
    ACTIONS(151), 1,
      aux_sym__terminator_token1,
    ACTIONS(153), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_STAR_STAR,
  [1754] = 3,
    ACTIONS(151), 1,
      aux_sym__terminator_token1,
    ACTIONS(251), 1,
      anon_sym_STAR_STAR,
    ACTIONS(153), 6,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1769] = 2,
    ACTIONS(326), 1,
      sym_integer,
    ACTIONS(324), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1781] = 6,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(328), 1,
      anon_sym_SEMI,
    ACTIONS(330), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
  [1800] = 6,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
    ACTIONS(332), 1,
      aux_sym__terminator_token1,
    ACTIONS(335), 1,
      anon_sym_SEMI,
    STATE(33), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
  [1819] = 6,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(338), 1,
      anon_sym_SEMI,
    ACTIONS(340), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
  [1838] = 6,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
  [1857] = 6,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(269), 1,
      anon_sym_SEMI,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
  [1876] = 6,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(342), 1,
      anon_sym_SEMI,
    ACTIONS(344), 1,
      anon_sym_RPAREN,
    STATE(23), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
  [1895] = 6,
    ACTIONS(44), 1,
      aux_sym__terminator_token1,
    ACTIONS(265), 1,
      anon_sym_SEMI,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym__terminator,
    STATE(55), 1,
      aux_sym__terminator_repeat1,
    STATE(86), 1,
      aux_sym_expression_block_repeat1,
  [1914] = 3,
    ACTIONS(346), 1,
      anon_sym_def,
    ACTIONS(349), 1,
      anon_sym_end,
    STATE(92), 2,
      sym_function_definition,
      aux_sym_module_block_repeat1,
  [1925] = 3,
    ACTIONS(351), 1,
      anon_sym_def,
    ACTIONS(353), 1,
      anon_sym_end,
    STATE(92), 2,
      sym_function_definition,
      aux_sym_module_block_repeat1,
  [1936] = 3,
    ACTIONS(351), 1,
      anon_sym_def,
    ACTIONS(355), 1,
      anon_sym_end,
    STATE(93), 2,
      sym_function_definition,
      aux_sym_module_block_repeat1,
  [1947] = 2,
    ACTIONS(357), 1,
      anon_sym_do,
    STATE(97), 1,
      sym_function_block,
  [1954] = 1,
    ACTIONS(312), 2,
      anon_sym_def,
      anon_sym_end,
  [1959] = 1,
    ACTIONS(304), 2,
      anon_sym_def,
      anon_sym_end,
  [1964] = 2,
    ACTIONS(359), 1,
      anon_sym_do,
    STATE(69), 1,
      sym_function_block,
  [1971] = 2,
    ACTIONS(361), 1,
      anon_sym_do,
    STATE(68), 1,
      sym_module_block,
  [1978] = 1,
    ACTIONS(296), 2,
      anon_sym_def,
      anon_sym_end,
  [1983] = 2,
    ACTIONS(363), 1,
      anon_sym_LPAREN,
    STATE(98), 1,
      sym_parameter_list,
  [1990] = 2,
    ACTIONS(363), 1,
      anon_sym_LPAREN,
    STATE(95), 1,
      sym_parameter_list,
  [1997] = 1,
    ACTIONS(365), 1,
      sym_identifier,
  [2001] = 1,
    ACTIONS(367), 1,
      anon_sym_RPAREN,
  [2005] = 1,
    ACTIONS(369), 1,
      sym_identifier,
  [2009] = 1,
    ACTIONS(371), 1,
      ts_builtin_sym_end,
  [2013] = 1,
    ACTIONS(373), 1,
      anon_sym_do,
  [2017] = 1,
    ACTIONS(375), 1,
      sym_alias,
  [2021] = 1,
    ACTIONS(377), 1,
      sym_identifier,
  [2025] = 1,
    ACTIONS(379), 1,
      sym_identifier,
  [2029] = 1,
    ACTIONS(381), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 38,
  [SMALL_STATE(6)] = 76,
  [SMALL_STATE(7)] = 114,
  [SMALL_STATE(8)] = 145,
  [SMALL_STATE(9)] = 176,
  [SMALL_STATE(10)] = 207,
  [SMALL_STATE(11)] = 238,
  [SMALL_STATE(12)] = 269,
  [SMALL_STATE(13)] = 297,
  [SMALL_STATE(14)] = 325,
  [SMALL_STATE(15)] = 353,
  [SMALL_STATE(16)] = 381,
  [SMALL_STATE(17)] = 409,
  [SMALL_STATE(18)] = 437,
  [SMALL_STATE(19)] = 465,
  [SMALL_STATE(20)] = 493,
  [SMALL_STATE(21)] = 521,
  [SMALL_STATE(22)] = 549,
  [SMALL_STATE(23)] = 577,
  [SMALL_STATE(24)] = 605,
  [SMALL_STATE(25)] = 624,
  [SMALL_STATE(26)] = 649,
  [SMALL_STATE(27)] = 674,
  [SMALL_STATE(28)] = 691,
  [SMALL_STATE(29)] = 708,
  [SMALL_STATE(30)] = 733,
  [SMALL_STATE(31)] = 758,
  [SMALL_STATE(32)] = 783,
  [SMALL_STATE(33)] = 806,
  [SMALL_STATE(34)] = 831,
  [SMALL_STATE(35)] = 848,
  [SMALL_STATE(36)] = 865,
  [SMALL_STATE(37)] = 882,
  [SMALL_STATE(38)] = 907,
  [SMALL_STATE(39)] = 924,
  [SMALL_STATE(40)] = 949,
  [SMALL_STATE(41)] = 966,
  [SMALL_STATE(42)] = 991,
  [SMALL_STATE(43)] = 1016,
  [SMALL_STATE(44)] = 1041,
  [SMALL_STATE(45)] = 1066,
  [SMALL_STATE(46)] = 1091,
  [SMALL_STATE(47)] = 1116,
  [SMALL_STATE(48)] = 1133,
  [SMALL_STATE(49)] = 1163,
  [SMALL_STATE(50)] = 1193,
  [SMALL_STATE(51)] = 1223,
  [SMALL_STATE(52)] = 1253,
  [SMALL_STATE(53)] = 1283,
  [SMALL_STATE(54)] = 1313,
  [SMALL_STATE(55)] = 1328,
  [SMALL_STATE(56)] = 1347,
  [SMALL_STATE(57)] = 1364,
  [SMALL_STATE(58)] = 1379,
  [SMALL_STATE(59)] = 1402,
  [SMALL_STATE(60)] = 1417,
  [SMALL_STATE(61)] = 1432,
  [SMALL_STATE(62)] = 1449,
  [SMALL_STATE(63)] = 1470,
  [SMALL_STATE(64)] = 1485,
  [SMALL_STATE(65)] = 1500,
  [SMALL_STATE(66)] = 1515,
  [SMALL_STATE(67)] = 1530,
  [SMALL_STATE(68)] = 1544,
  [SMALL_STATE(69)] = 1558,
  [SMALL_STATE(70)] = 1572,
  [SMALL_STATE(71)] = 1586,
  [SMALL_STATE(72)] = 1600,
  [SMALL_STATE(73)] = 1614,
  [SMALL_STATE(74)] = 1627,
  [SMALL_STATE(75)] = 1640,
  [SMALL_STATE(76)] = 1653,
  [SMALL_STATE(77)] = 1666,
  [SMALL_STATE(78)] = 1679,
  [SMALL_STATE(79)] = 1692,
  [SMALL_STATE(80)] = 1705,
  [SMALL_STATE(81)] = 1722,
  [SMALL_STATE(82)] = 1741,
  [SMALL_STATE(83)] = 1754,
  [SMALL_STATE(84)] = 1769,
  [SMALL_STATE(85)] = 1781,
  [SMALL_STATE(86)] = 1800,
  [SMALL_STATE(87)] = 1819,
  [SMALL_STATE(88)] = 1838,
  [SMALL_STATE(89)] = 1857,
  [SMALL_STATE(90)] = 1876,
  [SMALL_STATE(91)] = 1895,
  [SMALL_STATE(92)] = 1914,
  [SMALL_STATE(93)] = 1925,
  [SMALL_STATE(94)] = 1936,
  [SMALL_STATE(95)] = 1947,
  [SMALL_STATE(96)] = 1954,
  [SMALL_STATE(97)] = 1959,
  [SMALL_STATE(98)] = 1964,
  [SMALL_STATE(99)] = 1971,
  [SMALL_STATE(100)] = 1978,
  [SMALL_STATE(101)] = 1983,
  [SMALL_STATE(102)] = 1990,
  [SMALL_STATE(103)] = 1997,
  [SMALL_STATE(104)] = 2001,
  [SMALL_STATE(105)] = 2005,
  [SMALL_STATE(106)] = 2009,
  [SMALL_STATE(107)] = 2013,
  [SMALL_STATE(108)] = 2017,
  [SMALL_STATE(109)] = 2021,
  [SMALL_STATE(110)] = 2025,
  [SMALL_STATE(111)] = 2029,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(103),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(108),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(6),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_block_repeat1, 2),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(58),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(58),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(105),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_block_repeat1, 2), SHIFT_REPEAT(44),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, .production_id = 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, .production_id = 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 3),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 6),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 6),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__top_level, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__top_level, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 5),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 5),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 4),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 4),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 2, .production_id = 1),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_op, 2, .production_id = 1),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 2),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 2),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__terminator, 1),
  [279] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__terminator_repeat1, 2), SHIFT_REPEAT(56),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__terminator_repeat1, 2),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_block_repeat1, 1),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_block_repeat1, 1),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_block, 2),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_block, 2),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 3),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_definition, 3),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_block, 3),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_block, 3),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_block, 3),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_block, 3),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_block, 2),
  [318] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_block, 2),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_block_repeat1, 2),
  [322] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__terminator, 2),
  [326] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__terminator, 2),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [330] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [332] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(55),
  [335] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_block_repeat1, 2), SHIFT_REPEAT(33),
  [338] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [340] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [342] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [344] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [346] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_block_repeat1, 2), SHIFT_REPEAT(111),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_block_repeat1, 2),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [371] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_clia(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
